spring:
  application:
    name: user-server
  flyway:
    #到新的环境中数据库中有数据，且没有flyway_schema_history表时，是否执行迁移操作,如果设置为false，在启动时会报错，并停止迁移;如果为true,则生成history表并完成所有的迁移，要根据实际情况设置;
    baseline-on-migrate: true
    enabled: false
    #脚本位置
    locations:
      - classpath:db/mysql
    #在迁移时，是否校验脚本，假设V1.0__初始.sql已经迁移过了，在下次启动时会校验该脚本是否有变更过，则抛出异常
    validate-on-migrate: true
    clean-disabled: true
  datasource:
    #    url: jdbc:h2:mem:test
    url: jdbc:mysql://121.37.135.240:3306/jeecg-boot?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    #    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    #    data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    #    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    platform: h2
    #初始化数据库
  #    initialization-mode: always
  h2:
    console:
      enabled: true
server:
  port: 2080
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://test:123456@localhost:1080/eureka/
      # 缓存清单的更新时间，默认30秒
    registry-fetch-interval-seconds: 30
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/xml/*.xml
  type-aliases-package: com.cti.crm.user.entity
logback:
  path: F:\\www\\crm\\logs\\${spring.application.name}
#seata:
#  application-id:
#  tx-service-group:
#  service:
#    vgroup-mapping:
test:
  name: cui